version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "50051:50051"
      - "8081:8081"
    environment:
      - TLS=${TLS:-0}

  gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.gateway
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=50051
      - GATEWAY_PORT=50052
      - REST_PORT=8080
      - TLS=${TLS:-0}
      - PROTOCOL=${PROTOCOL:-}
    ports:
      - "50052:50052"
      - "8080:8080"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - TLS=${TLS:-0}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway
