sonar.projectKey=null-pointer-sch_grpc-boundary-lab
sonar.organization=null-pointer-sch

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=grpc-boundary-lab
#sonar.projectVersion=1.0

# Path to sources
sonar.sources=backend,frontend/src
sonar.tests=backend,frontend/src
sonar.test.inclusions=backend/**/*_test.go, frontend/src/**/*.spec.ts, frontend/src/**/*.test.ts, frontend/src/**/*.test.tsx
sonar.exclusions=backend/internal/proto/**, **/*.pb.go, frontend/node_modules/**, frontend/dist/**, frontend/src/assets/**, backend/internal/proto/ping.pb.go, backend/internal/proto/ping_grpc.pb.go, frontend/src/tests/setup.ts, frontend/src/**/*.test.tsx, frontend/src/**/*.test.ts, frontend/src/**/*.spec.ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Go specific configuration
sonar.go.coverage.reportPaths=backend/coverage.out

# JavaScript/TypeScript specific configuration
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
