FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -buildvcs=false -o /backend ./cmd/backend

FROM alpine:3.19
COPY --from=builder /backend /backend
EXPOSE 50051
EXPOSE 50151
EXPOSE 8081
EXPOSE 8181
ENTRYPOINT ["/backend"]
