name: Pipeline

on:
  push:
    branches: [main, update/repo-refactor]
  pull_request:
    branches: [main, update/repo-refactor]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    uses: null-pointer-sch/cicd-templates/.github/workflows/go-ci.yml@main
    with:
      go-version: "1.26"
      working-directory: "backend"

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Run Backend Tests with Coverage
        run: |
          cd backend
          go test -v -coverprofile=coverage.out ./...
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docs:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/update/repo-refactor')
    uses: null-pointer-sch/cicd-templates/.github/workflows/mkdocs-pages.yml@main
    with:
      python-version: "3.12"
      working-directory: "docs"
    permissions:
      contents: read
      pages: write
      id-token: write

  build-backend:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/update/repo-refactor')
    uses: null-pointer-sch/cicd-templates/.github/workflows/docker-build-push.yml@main
    with:
      image-name: "backend"
      project-id: "grpc-boundary-lab"
      repo-name: "grpc-boundary-lab-eu"
      region: "europe-west1"
      dockerfile-path: "backend/Dockerfile.backend"
      docker-context: "backend"
    secrets:
      GCP_WIF_PROVIDER: "projects/957364549513/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      GCP_SERVICE_ACCOUNT: "github-actions-deploy@grpc-boundary-lab.iam.gserviceaccount.com"

  build-gateway:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/update/repo-refactor')
    uses: null-pointer-sch/cicd-templates/.github/workflows/docker-build-push.yml@main
    with:
      image-name: "gateway"
      project-id: "grpc-boundary-lab"
      repo-name: "grpc-boundary-lab-eu"
      region: "europe-west1"
      dockerfile-path: "backend/Dockerfile.gateway"
      docker-context: "backend"
    secrets:
      GCP_WIF_PROVIDER: "projects/957364549513/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      GCP_SERVICE_ACCOUNT: "github-actions-deploy@grpc-boundary-lab.iam.gserviceaccount.com"

  deploy-infra:
    needs: [build-backend, build-gateway]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/update/repo-refactor')
    uses: null-pointer-sch/cicd-templates/.github/workflows/terraform-deploy.yml@main
    with:
      project-id: "grpc-boundary-lab"
      region: "europe-west1"
      artifact-repo-id: "grpc-boundary-lab-eu"
      working-directory: "backend/deploy/terraform"
      extra-tf-vars: "-var=\"image_tag_backend=${{ github.sha }}\" -var=\"image_tag_gateway=${{ github.sha }}\""
    secrets:
      GCP_WIF_PROVIDER: "projects/957364549513/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      GCP_SERVICE_ACCOUNT: "github-actions-deploy@grpc-boundary-lab.iam.gserviceaccount.com"
